version: "3.8"

services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      - GUILD_ID=${GUILD_ID}
    
    volumes:
      - data:/data
    
    restart: always

volumes:
  data:
    driver: local
